### ISSUE TITLE
请问这个是手工翻译 的还是用工具翻译的~~~

### ISSUE THREAD

**Issue by 625781186** [theall/QtPropertyBrowserV2.6-for-pyqt5#1]

**Comment by fulkfour** [comment]
写了个脚本翻译，然后手工去除bug


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"625781186"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月5日(星期天) 晚上11:11
收件人:&nbsp;"theall/QtPropertyBrowserV2.6-for-pyqt5"<QtPropertyBrowserV2.6-for-pyqt5@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[theall/QtPropertyBrowserV2.6-for-pyqt5] 请问这个是手工翻译 的还是用工具翻译的~~~ (#1)

**Comment by 625781186** [comment]
@theall 
@fulkfour 
请问脚本能发一份让我学习学习吗 
![image](https://user-images.githubusercontent.com/30521429/71800844-2149d000-3094-11ea-81c6-e3d72dfe9f98.png)

我邮箱: 625781186@qq.com

**Comment by theall** [comment]
你要这脚本做啥，这脚本做的很烂，我都不好意思发




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"625781186"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月6日(星期一) 下午3:16
收件人:&nbsp;"theall/QtPropertyBrowserV2.6-for-pyqt5"<QtPropertyBrowserV2.6-for-pyqt5@noreply.github.com&gt;;
抄送:&nbsp;"theall"<wazcd_1608@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [theall/QtPropertyBrowserV2.6-for-pyqt5] 请问这个是手工翻译 的还是用工具翻译的~~~ (#1)




@theall
 @fulkfour
 请问脚本能发一份让我学习学习吗
 
 
我邮箱: 625781186@qq.com

**Comment by theall** [comment]
> @theall
> @fulkfour
> 请问脚本能发一份让我学习学习吗
> ![image](https://user-images.githubusercontent.com/30521429/71800844-2149d000-3094-11ea-81c6-e3d72dfe9f98.png)
> 
> 我邮箱: [625781186@qq.com](mailto:625781186@qq.com)

只是用脚本正则表达式做了个初步处理，其实大部分都是手工做的
