### ISSUE TITLE
Ambiguous license

### ISSUE THREAD

**Issue by LumaRay** [theall/QtPropertyBrowserV2.6-for-pyqt5#2]
Hi! Can you explain what license does this property browser have?
If I look into sources - I see BSD license in them all.
But in the main directory I see GPL license file.
So what is the license in the end?
Can you fix overal license file or edit and fix all the source files?

**Comment by LumaRay** [comment]
Actually I like this widget and I need to use it in my application, but I am not allowed to publich my entire sources, so GPL license is very inconvetient... BSD is much better...

**Comment by fulkfour** [comment]
Hi Laykov,
&nbsp; &nbsp; I like BSD too!However,this project is translated from QtPropertyBrowser2.6(c++ version) which is licensed under GPL3.0, so im not sure wherther this project can use BSD or not, i need to consult the original author of&nbsp; QtPropertyBrowser, and give you a specific answer.


Regards
Theall




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yury Laykov"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月23日(星期二) 下午4:28
收件人:&nbsp;"theall/QtPropertyBrowserV2.6-for-pyqt5"<QtPropertyBrowserV2.6-for-pyqt5@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [theall/QtPropertyBrowserV2.6-for-pyqt5] Ambiguous license (#2)





 
Actually I like this widgetz and I need to use it in my application, but I am not allowed to publich my entire sources, so GPL license is very inconvetient... BSD is much better...

**Comment by theall** [comment]
The licence has been changed to BSD2.0.

**Comment by LumaRay** [comment]
Wow thank you!
